-- Migration 011: Create zerotouch_wiki_pages table
-- Wiki pages generated by the Phase 3 Ingest process.
-- Each page represents an integrated knowledge unit built from one or more Facts.

CREATE TABLE IF NOT EXISTS public.zerotouch_wiki_pages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id TEXT NOT NULL,
  workspace_id UUID REFERENCES public.zerotouch_workspaces(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  theme TEXT,
  kind TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  version INTEGER NOT NULL DEFAULT 1,
  source_fact_ids UUID[] NOT NULL DEFAULT '{}',
  last_ingest_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_zerotouch_wiki_pages_device_id
  ON public.zerotouch_wiki_pages(device_id);

CREATE INDEX IF NOT EXISTS idx_zerotouch_wiki_pages_device_updated
  ON public.zerotouch_wiki_pages(device_id, updated_at DESC);

ALTER TABLE public.zerotouch_wiki_pages ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'zerotouch_wiki_pages' AND policyname = 'zerotouch_wiki_pages_select'
  ) THEN
    CREATE POLICY "zerotouch_wiki_pages_select" ON public.zerotouch_wiki_pages FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'zerotouch_wiki_pages' AND policyname = 'zerotouch_wiki_pages_insert'
  ) THEN
    CREATE POLICY "zerotouch_wiki_pages_insert" ON public.zerotouch_wiki_pages FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'zerotouch_wiki_pages' AND policyname = 'zerotouch_wiki_pages_update'
  ) THEN
    CREATE POLICY "zerotouch_wiki_pages_update" ON public.zerotouch_wiki_pages FOR UPDATE USING (true);
  END IF;
END$$;
