-- Migration 016: Create zerotouch_action_candidates table
-- Action Candidate is the output of the Converter layer (Topic + Fact + context -> action draft).
-- For Slice 1 we keep this as a single table with embedded sources / review_state JSONB.
-- Action candidate sources / reviews / connector_drafts / connector_runs may be split into
-- separate tables in later slices when we add real connector integrations.

CREATE TABLE IF NOT EXISTS public.zerotouch_action_candidates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  topic_id UUID NOT NULL REFERENCES public.zerotouch_conversation_topics(id) ON DELETE CASCADE,
  device_id TEXT NOT NULL,
  workspace_id UUID REFERENCES public.zerotouch_workspaces(id) ON DELETE SET NULL,
  domain TEXT NOT NULL DEFAULT 'knowledge_worker',
  intent_type TEXT NOT NULL,
  title TEXT,
  summary TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  sources JSONB NOT NULL DEFAULT '{}'::jsonb,
  destination TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  confidence NUMERIC(3, 2),
  requires_review BOOLEAN NOT NULL DEFAULT true,
  review_state JSONB NOT NULL DEFAULT '{}'::jsonb,
  provider TEXT,
  model TEXT,
  generation_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_zerotouch_action_candidates_topic_id
  ON public.zerotouch_action_candidates(topic_id);

CREATE INDEX IF NOT EXISTS idx_zerotouch_action_candidates_device_status
  ON public.zerotouch_action_candidates(device_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_zerotouch_action_candidates_intent_type
  ON public.zerotouch_action_candidates(intent_type);

COMMENT ON TABLE public.zerotouch_action_candidates IS
  'ZeroTouch: action candidates generated by the Converter layer. Drafts to be reviewed before export.';
COMMENT ON COLUMN public.zerotouch_action_candidates.intent_type IS
  'e.g. email_draft, slack_message_draft, meeting_request, decision_log, etc.';
COMMENT ON COLUMN public.zerotouch_action_candidates.payload IS
  'Intent-specific structured draft. For email_draft: {recipient, subject, body, tone}.';
COMMENT ON COLUMN public.zerotouch_action_candidates.sources IS
  'Traceability info: source_quote, fact_ids, session_ids, topic_id snapshot.';
COMMENT ON COLUMN public.zerotouch_action_candidates.status IS
  'pending | approved | rejected | exported | failed';
COMMENT ON COLUMN public.zerotouch_action_candidates.review_state IS
  'Review history: {reviewed_by, reviewed_at, action, edits, notes}.';

ALTER TABLE public.zerotouch_action_candidates ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'zerotouch_action_candidates'
      AND policyname = 'zerotouch_action_candidates_select'
  ) THEN
    CREATE POLICY "zerotouch_action_candidates_select"
      ON public.zerotouch_action_candidates FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'zerotouch_action_candidates'
      AND policyname = 'zerotouch_action_candidates_insert'
  ) THEN
    CREATE POLICY "zerotouch_action_candidates_insert"
      ON public.zerotouch_action_candidates FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'zerotouch_action_candidates'
      AND policyname = 'zerotouch_action_candidates_update'
  ) THEN
    CREATE POLICY "zerotouch_action_candidates_update"
      ON public.zerotouch_action_candidates FOR UPDATE USING (true);
  END IF;
END$$;
